# Generated by Django 5.0.2 on 2024-02-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_alter_room_options_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
