# Generated by Django 5.0.1 on 2024-02-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
